### PR TITLE
 #79 added tooltip for sign up password criteria

### PR DESCRIPTION
**Pull request by Kresten24**

### CODE REVIEW

**Comment by MattYu** [comment]
capture-14
Hi Kresten, the tooltip is somewhat off-centered in my test scenario

**Comment by Kresten24** [comment]
capture123

Hi, thank you Mattyu.
I made changes it should work now.

**Review by MattYu — APPROVED** [review]
Awesome. Looks great

**Review by JoComp27 — APPROVED** [review]
This looks great!
Nice work!

**Pull request merged**
