### PR TITLE
Sa1#6 Adding Composer and Dependencies to the project

### PR DESCRIPTION
**Pull request by JoComp27**
Added Composer & several dependencies to the project: #43 
- AWS sdk
- PHPUnit

- Should fix TravisCI as it requires PHPUnit that we currently have now
- Also Added files from the master build of (14/02/18) to make the transition merge easier

### CODE REVIEW

**Review by MattYu — CHANGES_REQUESTED** [review]
Hi Jo, is Travis CI possible as a standalone?  I'm not sure that dumping half a million lines of code for Composer along with 3000 dependencies files in our repo is the best way of handling this -- just opening this preview page is making my chrome browser lag! 
 
Also, you are deleting home.php, signIn.html in this pull request and the branch version for .sql, signup.css, sql_connector.php is not updated and behind current master branch; this file will reverse a few recent commits. 

Thanks!

**Comment by MattYu** [comment]
I saw the files you added for AWS. Tbh, I believe there's too many potential critical points of failures with this - it would be a nightmare for future sprints integration if we go ahead with Composer...

We are not using and won't be using any external PHP libraries in this project requiring dependency management - it doesn't make sense to have half a million lines of code on our repo to handle a service that we don't need and having to deal with all the later hassles that comes along with it.  For our project, this tool will hinder us rather than help us.

**Review by refatK — CHANGES_REQUESTED** [review]
I think certain files in your branch can be git ignored.

https://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder

Also here's a useful site that helps you figure out what you can ignore:
https://www.gitignore.io/

Here's what I got when I looked for composer:
https://www.gitignore.io/api/composer

**Comment by refatK** [comment]
@JoComp27 

If you composer install in the travis.yml, you shouldn't have any issues of travis not having the necessary dependencies to do its job.

https://stackoverflow.com/questions/40965136/symfony-travis-ci-heroku-github-basic-gitignore-and-travis-yml

**Comment by JoComp27** [comment]
Hello everyone,

Concerning @MattYu and @refatK 's change requests,
- The removes files remaining of the branch are .html files, which, we do not use and have a .php double
- I added the gitignore in this branch to not include the 3000+ files from the /vendor directory

**Comment by MattYu** [comment]
Awesome work Jo! 

Would it possible to make a new clean pull request with all the work you've added? This would help me a lot by making to have a better big picture of all the work you've done.

**Review by MattYu — APPROVED** [review]

**Comment by JoComp27** [comment]
Will create a clean new pull request

**Comment by JoComp27** [comment]
Making a duplicate pull request doesn't change anything

**Comment by MattYu** [comment]
@JoComp27  okay, thanks for trying! I think you might need to create a new branch and make a pull request from that one. 

The reason for a new pull request is that Github only allows us to review/compare individual commits added to a branch  one at a time after a pull request has already been in place. But in this case, since they are 21 subsequent commits, it would be better if we were able to see and review all them at once to get a better bigger picture instead of each individually.

**Comment by JoComp27** [comment]
will make a new branch

**Pull request closed without merging**
